apiVersion: v1
kind: Template
metadata:
  name: "apicast-example-policy"
message: "APIcast Example Policy"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-policy

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/image.insecureRepository: "true"
    labels:
      app: apicast
    name: apicast-example-policy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apicast-policy:example
    source:
      git:
        uri: https://github.com/zhanggx-git/apicast-example-policy.git
        ref: 'master'
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          #kind: ImageStreamTag
          #name: 'amp-apicast-demo:${AMP_RELEASE}'
          kind: DockerImage
          name: registry.paas-test.eubrmb.com:5000/3scale-amp26/apicast-gateway-demo

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-custom-policies
  spec:
    nodeSelector: null
    output:
      to:
        #kind: ImageStreamTag
        #name: 'amp-apicast-demo:latest'
        kind: DockerImage
        name: registry.paas-test.eubrmb.com:5000/3scale-amp26/apicast-gateway-demo
    postCommit:
      args:
        - '--test'
        - '--lazy'
      command:
        - bin/apicast
    resources: {}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            name: 'apicast-policy:example'
          paths:
            # copy policy source code into the new image
            - destinationDir: policies
              sourcePath: /opt/app-root/policies/custom_example
            - destinationDir: policies
              sourcePath: /opt/app-root/policies/custom_example2
            # copy also installed dependencies to the policy folder, so they are vendored
            # - destinationDir: policies/example/0.1/resty/
            #   sourcePath: /opt/app-root/src/lua_modules/share/lua/5.1/resty/iputils.lua
      type: Dockerfile
      dockerfile: |
        FROM scratch
        COPY . src

    strategy:
      dockerStrategy:
        from:
          #kind: ImageStreamTag
          #name: 'amp-apicast-demo:${AMP_RELEASE}'
          kind: DockerImage
          name: registry.paas-test.eubrmb.com:5000/3scale-amp26/apicast-gateway-demo
      type: Docker
    triggers:
      - type: ConfigChange
      - type: ImageChange

parameters:
- name: AMP_RELEASE
  required: true
  description: AMP Version (eg. 2.2.0-GA)
  value: "2.6"
